using ModularShop.Kernel.Domain;

namespace ModularShop.Modules.Shipping.Domain;

/// <summary>
/// A shipment, owned by the Shipping module. A shipment is created from an <c>OrderPlaced</c>
/// integration event — Shipping only ever learns about an order through that event, never by reading the
/// Sales tables. It keeps just the order info it needs (a copy), plus its own state. <see cref="CustomerId"/>
/// is a foreign key to the <b>shared kernel</b> <see cref="Customer"/> — the same customer the Sales
/// order referenced — so deliveries and orders point at one consistent customer record.
/// </summary>
public sealed class Shipment : Entity
{
    private readonly List<ShipmentItem> _items = new();

    public string ShipmentNumber { get; private set; } = default!;
    public Guid OrderId { get; private set; }
    public string OrderNumber { get; private set; } = default!;
    public Guid CustomerId { get; private set; }
    public string CustomerName { get; private set; } = default!;
    public ShipmentStatus Status { get; private set; }
    public DateTime CreatedOnUtc { get; private set; }
    public DateTime? ShippedOnUtc { get; private set; }
    public DateTime? DeliveredOnUtc { get; private set; }
    public string? Carrier { get; private set; }
    public string? TrackingNumber { get; private set; }

    public IReadOnlyCollection<ShipmentItem> Items => _items;
    public int TotalUnits => _items.Sum(i => i.Quantity);

    private Shipment() { } // EF

    public Shipment(string shipmentNumber, Guid orderId, string orderNumber, Guid customerId,
        string customerName, DateTime createdOnUtc, Guid id = default)
        : base(id)
    {
        ShipmentNumber = shipmentNumber;
        OrderId = orderId;
        OrderNumber = orderNumber;
        CustomerId = customerId;
        CustomerName = customerName;
        CreatedOnUtc = createdOnUtc;
        Status = ShipmentStatus.Pending;
    }

    // The item's own id is generated by EF; its ShipmentId FK is set by EF from this Items navigation on save.
    public void AddItem(string productName, int quantity) => _items.Add(new ShipmentItem(productName, quantity));

    public bool Ship(string carrier, string trackingNumber)
    {
        if (Status != ShipmentStatus.Pending) return false;
        Status = ShipmentStatus.Shipped;
        Carrier = carrier;
        TrackingNumber = trackingNumber;
        ShippedOnUtc = DateTime.UtcNow;
        return true;
    }

    public bool Deliver()
    {
        if (Status != ShipmentStatus.Shipped) return false;
        Status = ShipmentStatus.Delivered;
        DeliveredOnUtc = DateTime.UtcNow;
        return true;
    }

    /// <summary>Used only by seeding, to place a historical shipment into a known past state.</summary>
    public void ApplySeedState(ShipmentStatus status, string? carrier, string? trackingNumber, DateTime? shippedOnUtc, DateTime? deliveredOnUtc)
    {
        Status = status;
        Carrier = carrier;
        TrackingNumber = trackingNumber;
        ShippedOnUtc = shippedOnUtc;
        DeliveredOnUtc = deliveredOnUtc;
    }
}
